language: ruby
sudo: false
dist: precise
rvm:
  - 2.5.5
  - 2.6.2
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
  - bundler --version
cache: bundler
script:
  bundle exec rake test
